#lang racket
(require "env.rkt"
         "eval.rkt")
(provide default-env)

(define (straw-add . args)
  (for ([a args])
    (unless (number? a)
      (error "expected number")))
  (apply + args))

(define (straw-sub . args)
  (for ([a args])
    (unless (number? a)
      (error "expected number")))
  (apply - args))

(define (straw-mul . args)
  (for ([a args])
    (unless (number? a)
      (error "expected number")))
  (apply * args))

(define (straw-div . args)
  (for ([a args])
    (unless (number? a)
      (error "expected number")))
  (when (< (length args) 2)
    (error "arity mismatch"))
  (for ([a (cdr args)])
    (when (zero? a)
      (error "division by zero")))
  (define result (apply / args))
  (if (exact? result)
      (if (integer? result)
          result
          (exact->inexact result))
      result))

(define (straw-mod a b)
  (unless (number? a) (error "expected number"))
  (unless (number? b) (error "expected number"))
  (when (zero? b) (error "division by zero"))
  (modulo a b))

(define (make-numeric-comparator op)
  (lambda (a b)
    (unless (number? a) (error "expected number"))
    (unless (number? b) (error "expected number"))
    (op a b)))

(define straw-< (make-numeric-comparator <))
(define straw-> (make-numeric-comparator >))
(define straw-<= (make-numeric-comparator <=))
(define straw->= (make-numeric-comparator >=))
(define straw-= (make-numeric-comparator =))

(define (straw-equal? a b)
  (equal? a b))

(define (straw-cons a b)
  (cons a b))

(define (straw-car p)
  (unless (pair? p)
    (error "car: expected pair"))
  (car p))

(define (straw-cdr p)
  (unless (pair? p)
    (error "cdr: expected pair"))
  (cdr p))

(define (straw-list . args)
  args)

(define (straw-null? x)
  (null? x))

(define (straw-pair? x)
  (pair? x))

(define (straw-not x)
  (eq? x #f))

(define (straw-number? x) (number? x))
(define (straw-string? x) (string? x))
(define (straw-symbol? x) (symbol? x))
(define (straw-boolean? x) (boolean? x))
(define (straw-procedure? x) (or (closure? x) (procedure? x)))

(define (straw-display x)
  (display x)
  (void))

(define (straw-newline)
  (newline)
  (void))

(define (default-env)
  (define e (make-env))
  (env-set! e '+ straw-add)
  (env-set! e '- straw-sub)
  (env-set! e '* straw-mul)
  (env-set! e '/ straw-div)
  (env-set! e 'mod straw-mod)
  (env-set! e '< straw-<)
  (env-set! e '> straw->)
  (env-set! e '<= straw-<=)
  (env-set! e '>= straw->=)
  (env-set! e '= straw-=)
  (env-set! e 'equal? straw-equal?)
  (env-set! e 'cons straw-cons)
  (env-set! e 'car straw-car)
  (env-set! e 'cdr straw-cdr)
  (env-set! e 'list straw-list)
  (env-set! e 'null? straw-null?)
  (env-set! e 'pair? straw-pair?)
  (env-set! e 'not straw-not)
  (env-set! e 'number? straw-number?)
  (env-set! e 'string? straw-string?)
  (env-set! e 'symbol? straw-symbol?)
  (env-set! e 'boolean? straw-boolean?)
  (env-set! e 'procedure? straw-procedure?)
  (env-set! e 'display straw-display)
  (env-set! e 'newline straw-newline)
  e)
